"""Added new field to memo model

Revision ID: 43cb20f90b60
Revises: 46ca46178a36
Create Date: 2023-09-07 18:42:20.179397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43cb20f90b60'
down_revision = '46ca46178a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_image', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo', schema=None) as batch_op:
        batch_op.drop_column('linked_image')

    # ### end Alembic commands ###
