"""Added relationship

Revision ID: 98397706c710
Revises: 90373d7cf1ea
Create Date: 2023-09-10 18:34:30.913529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98397706c710'
down_revision = '90373d7cf1ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memos_labels',
    sa.Column('memd_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['memd_id'], ['memo.id'], ),
    sa.PrimaryKeyConstraint('memd_id', 'label_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memos_labels')
    # ### end Alembic commands ###
